name: dotnet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.8'
    - uses: microsoft/setup-msbuild@v1
    - uses: dotnet/nbgv@v0.4.0
      with:
        setAllVars: true
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
    - name: nuget restore
      run: nuget restore -NonInteractive
    - name: msbuild
      run: msbuild Unravel.sln /p:Configuration=Release /verbosity:normal /t:Rebuild

    - name: Start IIS Express
      run: |
        $URL = .\util\Start-IisExpress.ps1 -Path .\examples\Web
        if (!$URL) { exit 1 }
        "URL=$URL" | Out-File -Append -Encoding utf8 -FilePath $Env:GITHUB_ENV

    - name: Check Connection
      run: curl --insecure --show-error --silent $Env:URL

    - name: dotnet pack
      run: dotnet pack --configuration Release --no-build --output artifacts/
